### ISSUE TITLE
App crashes when reaching 16th

### ISSUE THREAD

**Issue by airon90** [NimaKhajehpour/GuessThatPokemon#12]
I select Italian language and all gen. After inserting the 15th name of the Pokémon and reaching the 16th Pokémon to be guessed, the app crashes.

**Comment by NimaKhajehpour** [comment]
I tested the app with italian and all gens. It did not crash for me. I have to look further into it. Thanks for the issue.

**Comment by NimaKhajehpour** [comment]
Yupp, you are right. the api does not have all the names for the languages other than english. so it returns empty name and then when im trying to get the name that is returned it will crash. so the main reason is that the api is not complete on the other languages. i will have to find a work around for that.

**Comment by NimaKhajehpour** [comment]
i had to exclude the pokemons that did not exist in the language, so some languages may be incomplete in pokemons names but that was the only way to solve the api lacking the names in all languages. but at least the app does not crash on other languages than english. also there were two languages that did not even have info in them which is weird that they included them in the api. but right now the problem is solved and the next update will have the bug fixed
