### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by supermamie** [NimaKhajehpour/GuessThatPokemon#7]
This is just a reminder.
As F-Droid only generte the app when a release is made, you should add one everytime there are new feature worthing it.

As the feature I requested are in the code, I would love to be able to test them 🙂

**Comment by NimaKhajehpour** [comment]
Hey there. Yeah i know that i did not get a new release for a reason 😅 although tge features are implemented in the app i did bump to some problems and bugs, on the other hand i got busy on my studies so sorry for the delay on release. I plan to solve the problems ASAP and publish the release.
Just for a heads up, when the new release gets published you might need to download the app from here (dont worry about your data it is a RB) because fdroid might have some problems building it.
Again sorry about the delay. Have a good day/night 😀
